name: dartEncoderFiles
description: A sample command-line application.
# version: 1.0.1
# author: Dko1905 <daniel.florescu05@yahoo.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  path: ^1.4.1
  dartToCharCode:
    path: /home/daniel/Documents/programs/dartToCharCode

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
