name: website_dart
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Dko1905 <daniel.florescu05@yahoo.com>

environment:
  sdk: '>=2.2.0 <3.0.0'
  firebase: ^5.0.0

dependencies:
  path: ^1.4.1
  dartToCharCode:
      path: /home/daniel/Documents/programs/dartToCharCode

dev_dependencies:
  build_runner: ^1.3.4
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
